# ---------- TRANSPARENCIA ----------
background_opacity 0.80

# Mejora visual (opcional pero recomendado)
background_blur 1

# Colores agradables en fondos oscuros
foreground #cdd6f4
background #1e1e2e
