general {
    lock_cmd = /home/chelo/.config/hypr/scripts/lock-session.sh
    before_sleep_cmd = /home/chelo/.config/hypr/scripts/lock-session.sh
}

listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

listener {
    timeout = 900
    on-timeout = /home/chelo/.config/hypr/scripts/suspend-deep.sh
}
