font=JetBrainsMono Nerd Font 11
background-color={{ colors.surface_container_highest.default.hex }}F2
text-color={{ colors.on_surface.default.hex }}
border-color={{ colors.outline.default.hex }}EB
progress-color=over {{ colors.primary.default.hex }}
border-size=1
border-radius=14
padding=12
margin=12
default-timeout=5000
group-by=app-name
icons=1
max-icon-size=48

[urgency=low]
border-color={{ colors.outline.default.hex }}A6

[urgency=normal]
background-color={{ colors.surface_container_highest.default.hex }}F2

[urgency=critical]
border-color={{ colors.error.default.hex }}

[mode=do-not-disturb]
invisible=1
